language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install -y curl g++ make
- pushd ~
- curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
- cd spatialindex-src-1.8.5
- ./configure
- make
- sudo make install
- sudo ldconfig
- popd
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
- pip install PyOpenGL
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  on:
    tags: true
    branch: master
  password:
    secure: VOZH/dHQLJN47zhKLZVImJiCz+hKcue+OyLVTkABSA3EPbusTj82adR+CxoUXwg9sBblHqtrOvcRNaoAIwo65OCSmAaefsHSLSbemiT26sg/uflbbYq6rkgkl9RR2VQE4628/OCSUfxw04hlOWGlWhMGvT5rkPloqzJjd2g8Al0mvViYXSitv9dolFVWGqP/09Mldmr4sOoMFaynUOIBhXguYggwvZ06KA0II2Y0CVGIoz/KTVOO7SQNDxKL4IedprLB4eG4toDWGa6rRpWYmoXWWYFep8HkLzenXm3rNKrZKUnwbYax6b0GlSdSktPHDhslSE084AJT96Q3besGl1PVYimaz0ZQyU6UpXcYWZERV3bHiH7ct7ZLBJxJFuQ+Gi26VOJ4bQ4FkPivpaUHdUsFLDOSIF4Lan8rRcMWZ7vKW9CfOD0KquJhHEuk94Z2Tq32FXYWmSfXWhgfswDBOy1QR9HAB6NgmLMfUVfb/dCnmKXYf5+x2WYeqYMLWjq4S4bdbQmIVcpgOSLSCxnAsmvWEnVQQNlReSSOSdt0agK8iw1Ln0U+9Pbw/jee3cXXImr1Kn/o3slIIVczkgtlAGyP4jcHTOfoSEqvG7LaEIjpGHr9IVpnY8F1KktaH1nph44eEkYwbwq5+3GpBjMIZNR56OiUHVuQQY9QbydrH5Q= 
  distributions: sdist bdist_wheel
notifications:
  email: false
