language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install -y curl g++ make
- pushd ~
- curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
- cd spatialindex-src-1.8.5
- ./configure
- make
- sudo make install
- sudo ldconfig
- popd
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
- pip install PyOpenGL
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  on:
    tags: true
    branch: master
  password:
    secure: cvUiUTNpOTZBs5pf0YXF0MseN53cPZSRlj+kDvG9uapi7tj64XSy7KnO2EO+sxbGKBmoaJdT9HsR/MfhL12MBCtFOsl8/uclhqWwNUi4XeKPomHIkcbkPel5Oie8bCG4gA8mWabAkjgag8xwIGtkbilTWpJyvWAlv4upHlzT0SqUr6OtRNgTh+h93QEhrCBjir+U7N5+RsNGfBL2930aWG6o6toWE0FEZ/gYRnhhFe7hsJZt8cvHFHPUdD0hiW+pUv0Wpba/F4Q3f1XZRfr1UQcYR/bYeDGriyu6TM5OriE6Yxluo8XLXiqpUhY0WvQYo4S/Z76Z+cxbTQDfTwvV+AFb1HrRnkU+DoyLk1r4FnhgVbITZrP191eX7IKB/l3c2fkgklCiB2qYHIsAmAdJKj2/A+BxUWTlsWzU9BVHe+tgkzsTm/0RBch57b4Z2qJ6roL+lGgRV5/B9tThvBAnz1aTobRBoTZBOJQvGQc9Tm31wbs7HoKUvP16G6lV07FtfF6ds5ryOJshdkmfWN9+eBzHewPsuCKB/hDiGpH8baav2TQ2IgJ9A4CZ/JXQVH4fROaXrzKSgj+FCfuYrU96QOkXCe+sSoGNdJXi8q9NeXylxu0ItQQkJOk5qYzEjeXIZDETuNIzxpZjSobPeKrQpLAqxCJ+kZnfsszkMYBz42g=
  distributions: sdist bdist_wheel
notifications:
  email: false
